---
services:
  web:
    container_name: newbrowser
    image: ghcr.io/fboaventura/dckr-newbrowser:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOMAIN: ""
    ports:
      - "8087:80"
#    volumes:
#      - ./data/extensions.json:/app/www/assets/data/extensions.json
