---
services:
  web:
    container_name: newbrowser
    image: fboaventura/dckr-newbrowser:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOMAIN: ""
    ports:
      - "8081:80"
    volumes:
      - ./www:/app/www
